In [153]:
#!pip install tensorflow

In [155]:
ls

 archive.zip
 LSTM-neural-network-architecture-Input-layer-consists-of-10-sequential-time-steps-10.png
'Next word prediction.ipynb'
 README.md
 sentence1.txt
 sentences.txt


In [223]:
# Open the file in read mode
with open('sentences.txt', 'r') as file:
    content = file.read()

# Print the content of the file
print(content)


The quick brown fox jumps over the lazy dog.
My Mum tries to be cool by saying that she likes all the same things that I do.
A purple pig and a green donkey flew a kite in the middle of the night and ended up sunburnt.
Last Friday I saw a spotted striped blue worm shake hands with a legless lizard.
A song can make or ruin a person’s day if they let it get to them.
Sometimes it is better to just walk away from things and go back to them later when you’re in a better frame of mind.
Writing a list of random sentences is harder than I initially thought it would be.
Lets all be unique together until we realise we are all the same.
If I don’t like something, I’ll stay away from it.
I love eating toasted cheese and tuna sandwiches.
If you like tuna and tomato sauce- try combining the two. It’s really not as bad as it sounds.
Someone I know recently combined Maple Syrup & buttered Popcorn thinking it would taste like caramel popcorn. It didn’t and they don’t recommend anyone else do it either.

In [225]:
# for sentence in content.split("\n"):
    # print(sentence)

In [227]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [229]:
# creating object of Tokenizer
tokenizer = Tokenizer()

In [231]:
tokenizer.fit_on_texts([content]) # it takes multiple input so pass it list

In [233]:
tokenizer.word_index # now check number assigned to every word

{'the': 1,
 'to': 2,
 'a': 3,
 'he': 4,
 'of': 5,
 'was': 6,
 'in': 7,
 'she': 8,
 'and': 9,
 'that': 10,
 'i': 11,
 'it': 12,
 'his': 13,
 'on': 14,
 'is': 15,
 'her': 16,
 'for': 17,
 'with': 18,
 'you': 19,
 'had': 20,
 'but': 21,
 'as': 22,
 'be': 23,
 'at': 24,
 'my': 25,
 'all': 26,
 'they': 27,
 'are': 28,
 'when': 29,
 'were': 30,
 'your': 31,
 'if': 32,
 'from': 33,
 'have': 34,
 'there': 35,
 'by': 36,
 'would': 37,
 'not': 38,
 'what': 39,
 'out': 40,
 'like': 41,
 'could': 42,
 'life': 43,
 'into': 44,
 'no': 45,
 'about': 46,
 'up': 47,
 'so': 48,
 'him': 49,
 'an': 50,
 'just': 51,
 'than': 52,
 'time': 53,
 'one': 54,
 'only': 55,
 'their': 56,
 'more': 57,
 'people': 58,
 'who': 59,
 'day': 60,
 'we': 61,
 'way': 62,
 "didn't": 63,
 'found': 64,
 'do': 65,
 'make': 66,
 'go': 67,
 'this': 68,
 'me': 69,
 'always': 70,
 'never': 71,
 'or': 72,
 'back': 73,
 'see': 74,
 'made': 75,
 'been': 76,
 'saw': 77,
 'best': 78,
 'until': 79,
 'eating': 80,
 'still': 81,
 'good': 8

In [235]:
len(tokenizer.word_index)

2619

In [237]:
# list_of_sentence = [] # just for understanding i am making list
# list_of_tokens = []
# for sentence in content.split("\n"):
#     list_of_sentence.append(sentence)
#     tokenizer.texts_to_sequences([sentence])
#     list_of_tokens.append(tokenizer.texts_to_sequences([sentence]))
#     print(tokenizer.texts_to_sequences([sentence])[0])


In [239]:
#ist_of_tokens[0]

In [241]:
#list_of_sentence[0]

In [243]:
end = 1
input_sentences = []
counter = 0
for sentence in content.split("\n"):
    counter = counter+1 
    tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]

    for start in range(1, len(tokenized_sentence)):
        final = tokenized_sentence[:start+end]
        input_sentences.append(final)
        #print(final) # 

In [245]:
counter # totel lines

724

In [247]:
maximum_length = max([len(sentence) for sentence in input_sentences])

In [249]:
maximum_length

29

In [251]:
# input_sentences

In [253]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

padded_text = pad_sequences(input_sentences, maxlen = maximum_length, padding= "pre" )

In [255]:
padded_text

array([[   0,    0,    0, ...,    0,    1,  514],
       [   0,    0,    0, ...,    1,  514,  907],
       [   0,    0,    0, ...,  514,  907,  515],
       ...,
       [   0,    0,    0, ...,  766,    2, 2618],
       [   0,    0,    0, ...,    2, 2618,    1],
       [   0,    0,    0, ..., 2618,    1, 2619]], dtype=int32)

In [257]:
# now build dataset
X = padded_text[:,:-1] 

In [259]:
X

array([[   0,    0,    0, ...,    0,    0,    1],
       [   0,    0,    0, ...,    0,    1,  514],
       [   0,    0,    0, ...,    1,  514,  907],
       ...,
       [   0,    0,    0, ...,   25,  766,    2],
       [   0,    0,    0, ...,  766,    2, 2618],
       [   0,    0,    0, ...,    2, 2618,    1]], dtype=int32)

In [261]:
X.shape

(8186, 28)

In [263]:
y = padded_text[:, -1]

In [265]:
y

array([ 514,  907,  515, ..., 2618,    1, 2619], dtype=int32)

In [267]:
y.shape

(8186,)

In [269]:
total_classes = len(tokenizer.word_index)

In [271]:
from tensorflow.keras.utils import to_categorical

y = to_categorical(y, num_classes = total_classes + 1) # total_classes are value in vocab and index start form 1 so last will not be count

In [273]:
y.shape

(8186, 2620)

In [275]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Embedding, Dense

In [277]:
import numpy as np

# Define the model
model = Sequential()
model.add(Embedding(total_classes+1, 100, input_length = maximum_length))  # Embedding layer 
model.add(LSTM(200, return_sequences=False))  # LSTM layer
model.add(Dense(total_classes+1, activation="softmax"))  # Dense layer (178 are total words in vocab, activation is softmax to get probabity of every word)

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Build the model with a sample input
sample_input = np.random.randint(0, total_classes, size=(1, 50))  # Example input (batch_size=1, sequence_length=50)
model(sample_input)

# Display the model summary
model.summary()

/home/dawood/anaconda3/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (1, 50, 100)           │       262,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_4 (LSTM)                   │ (1, 200)               │       240,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (1, 2620)              │       526,620 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,029,420 (3.93 MB)

 Trainable params: 1,029,420 (3.93 MB)

 Non-trainable params: 0 (0.00 B)

In [279]:
# total words 178 and every words is getting 100 is 100 demensional vector for every word 178*100 = 17800

In [281]:
X.shape

(8186, 28)

In [283]:
y.shape

(8186, 2620)

In [ ]:
model.fit(X,y, epochs=50)

Epoch 1/50
256/256 ━━━━━━━━━━━━━━━━━━━━ 21s 75ms/step - accuracy: 0.0558 - loss: 7.1364
Epoch 2/50
256/256 ━━━━━━━━━━━━━━━━━━━━ 19s 75ms/step - accuracy: 0.0621 - loss: 6.3920
Epoch 3/50
256/256 ━━━━━━━━━━━━━━━━━━━━ 19s 74ms/step - accuracy: 0.0666 - loss: 6.1753
Epoch 4/50
256/256 ━━━━━━━━━━━━━━━━━━━━ 26s 101ms/step - accuracy: 0.0746 - loss: 5.9492
Epoch 5/50
256/256 ━━━━━━━━━━━━━━━━━━━━ 46s 179ms/step - accuracy: 0.0918 - loss: 5.6406
Epoch 6/50
256/256 ━━━━━━━━━━━━━━━━━━━━ 62s 102ms/step - accuracy: 0.1025 - loss: 5.3198
Epoch 7/50
256/256 ━━━━━━━━━━━━━━━━━━━━ 23s 91ms/step - accuracy: 0.1183 - loss: 5.0244
Epoch 8/50
256/256 ━━━━━━━━━━━━━━━━━━━━ 41s 92ms/step - accuracy: 0.1361 - loss: 4.7124
Epoch 9/50
256/256 ━━━━━━━━━━━━━━━━━━━━ 42s 97ms/step - accuracy: 0.1556 - loss: 4.4007
Epoch 10/50
256/256 ━━━━━━━━━━━━━━━━━━━━ 21s 83ms/step - accuracy: 0.1881 - loss: 4.0859
Epoch 11/50


In [220]:
import numpy as np
import time
text = "She"

for i in range(10): 
    token_text = tokenizer.texts_to_sequences([text])[0]
    padded_text = pad_sequences([token_text], maxlen = maximum_length, padding= "pre" )

    pos = np.argmax(model.predict(padded_text))
    for word, index in tokenizer.word_index.items():
        if index == pos:
            text = text + " " + word
            print(text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 256ms/step
She was
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
She was too
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
She was too short
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
She was too short to
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
She was too short to see
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
She was too short to see over
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
She was too short to see over the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
She was too short to see over the fence
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
She was too short to see over the fence beats
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
She was too short to see over the fence beats manifesto
